{% set version = "2.1.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set cran_mirror = 'https://cran.r-project.org' %}

package:
  name: r-rfpermute
  version: {{ version|replace("-", "_") }}

source:
  fn: rfPermute_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rfPermute_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rfPermute/rfPermute_{{ version }}.tar.gz
  sha256: 33d76e20c905b349536e468f8a66f7a5642e9323edd30a4bd951b22691db1ba5

build:
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr
    - r-tidyr
    - r-viridis
    - r-abind
    - r-ggplot2
    - r-gridextra
    - r-randomforest
    - r-reshape2
    - r-swfscmisc >=1.1.1
  run:
    - r-base
    - r-dplyr
    - r-tidyr
    - r-viridis
    - r-abind
    - r-ggplot2
    - r-gridextra
    - r-randomforest
    - r-reshape2
    - r-swfscmisc >=1.1.1

test:
  commands:
    - $R -e "library('rfPermute')"           # [not win]
    - "\"%R%\" -e \"library('rfPermute')\""  # [win]

about:
  home: https://github.com/EricArcher/rfPermute
  license: GPL (>= 2)
  summary: Estimate significance of importance metrics for a Random Forest model by permuting
    the response variable. Produces null distribution of importance metrics for each
    predictor variable and p-value of observed. Provides summary and visualization functions
    for randomForest results.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
