{% set version = "2.5.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rfpermute
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rfPermute_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rfPermute/rfPermute_{{ version }}.tar.gz
  sha256: 3487d0ffed3a5d030ca7ae0f79e9037ca286f9dfd6301bbfb5ea171aa5281b18

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base >=4.0
    - r-abind
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-plyr
    - r-randomforest
    - r-reshape2
    - r-rlang
    - r-scales
    - r-swfscmisc >=1.1.1
    - r-tibble
    - r-tidyr
  run:
    - r-base >=4.0
    - r-abind
    - r-dplyr
    - r-ggplot2
    - r-gridextra
    - r-magrittr
    - r-plyr
    - r-randomforest
    - r-reshape2
    - r-rlang
    - r-scales
    - r-swfscmisc >=1.1.1
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('rfPermute')"           # [not win]
    - "\"%R%\" -e \"library('rfPermute')\""  # [win]

about:
  home: https://github.com/EricArcher/rfPermute
  license: GPL-2.0-or-later
  summary: Estimate significance of importance metrics for a Random Forest model by permuting the response variable. Produces null distribution of importance metrics for each predictor variable and p-value of observed. Provides summary and visualization functions for 'randomForest'  results.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut

# Package: rfPermute
# Type: Package
# Title: Estimate Permutation p-Values for Random Forest Importance Metrics
# Description: Estimate significance of importance metrics for a Random Forest model by permuting the response variable. Produces null distribution of importance metrics for each predictor variable and p-value of observed. Provides summary and visualization functions for 'randomForest'  results.
# Version: 2.1.7
# Authors@R: c( EA = person("Eric", "Archer", email = "eric.archer@noaa.gov", role = c("aut", "cre")))
# URL: https://github.com/EricArcher/rfPermute
# BugReports: https://github.com/EricArcher/rfPermute/issues
# Depends: R (>= 3.2.0), randomForest
# Imports: abind, dplyr, ggplot2, grDevices, gridExtra, magrittr, parallel, plyr, reshape2, rlang, scales, stats, swfscMisc (>= 1.1.1), tibble, tidyr, utils
# License: GPL (>= 2)
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-04-22 01:55:47 UTC; ericarcher
# Author: Eric Archer [aut, cre]
# Maintainer: Eric Archer <eric.archer@noaa.gov>
# Repository: CRAN
# Date/Publication: 2019-04-22 05:00:03 UTC
