appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: B6yYjnwNmczp9WvLEWQ2GVyo0WIy/ocavEEnY15BpaqB1PDrSHWtLsCOetTWL5OEOdBxzK0Z0P/Wz8x0QN5hK4G/UaiTV4Qkc11efgtYvyyTIjA1zL0MarEzS/neE7C+bWJqnv25byrG/0nqvXSZ1ZPK3PeXepVZbfMylgXRhLfE+mjuyXnvNqbUiXdIJLWYUMTUHR2aThlCxlyKlp/P9gpyA5JbGC7GoJuC2UdcgQHT5ClksU4YjoG0lvbZS9a3zBvXLHieL0M04qT928M1poitmwAU3m4wLt8EIQb45deog9AjF1P2IkxpCMdhXh/wRQjWkyI7/MBmqD1NZriLdpb7S1aaGKwwGoKN2U+MJzOLVFd4f5oRDR8QieehH7k9A/LtcG5c4PM8b3RkHPg86IhWr5qpDREG81F0Eu8wblWmZ7iEcTc/aaXDCENNUpTg4IyHJFM/TcofPFWr+8HEkTak5YG33gfn4dY68a+WqXdhJ6V4OyNS7EiDpWXOIderR3xfmI0HVWfJYxXtjQeo95TQvaRuF36e91gc4CoOyuw+Z5QOzqCH0CG131ihfsAdfj90xfFWNuoiKU6DKOdYMs0whd2eq5U8f+dafz8quWvYArO4+w+ZzMvGHpCHzmN6dhD6h+89DNFX/JluynaIoiCi665WNOG7tE1yormvNSE=}
